// Copies the compiled TaskVault ABI + bytecode from contracts/out into src/abi.ts.
// Run after `forge build` whenever the contract changes.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = JSON.parse(
  readFileSync(join(here, "../../../contracts/out/TaskVault.sol/TaskVault.json"), "utf8"),
);
const out = `// Generated by scripts/sync-abi.mjs from contracts/out — do not edit.
export const taskVaultAbi = ${JSON.stringify(artifact.abi)} as const;
export const taskVaultBytecode = "${artifact.bytecode.object}" as const;
`;
writeFileSync(join(here, "../src/abi.ts"), out);
console.log(
  "abi entries:",
  artifact.abi.length,
  "bytecode bytes:",
  artifact.bytecode.object.length / 2 - 1,
);
